# Generated by Django 4.1.3 on 2022-11-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_watchlist_listing_watchlist_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_starting_bid',
            field=models.BooleanField(default=False),
        ),
    ]
