# Generated by Django 4.1.3 on 2022-11-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_comments_is_starting_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='is_starting_bid',
        ),
    ]
