# Generated by Django 4.1.3 on 2023-01-03 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_like_following_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='userliked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
